<a href="https://colab.research.google.com/github/shreeramshanmugasundaram/PytorchLearning/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
# import numpy as np

In [5]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [6]:
# addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [7]:
# addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [8]:
# substraction

In [10]:
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [12]:
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [13]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [14]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [15]:
# division
tensor_a / tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [16]:
torch.div(tensor_a, tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [20]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [21]:
torch.remainder(tensor_a, tensor_b)

tensor([1, 2, 3, 4])

In [22]:
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [23]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [24]:
tensor_a

tensor([1, 2, 3, 4])

In [25]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [27]:
tensor_a = tensor_a+ tensor_b

In [28]:
tensor_a.add_(tensor_b)

tensor([11, 14, 17, 20])

In [29]:
tensor_a

tensor([11, 14, 17, 20])