<a href="https://colab.research.google.com/github/shreeramshanmugasundaram/PytorchLearning/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# tensor

In [2]:
import torch
import numpy as np

In [4]:
# list
my_list = [[1,2,3,4],[1,2,3,4]]
my_list

[[1, 2, 3, 4], [1, 2, 3, 4]]

In [6]:
#  numpy array
np1 = np.random.rand(3, 4)
np1

array([[0.39539698, 0.3948428 , 0.19581678, 0.52964686],
       [0.59426915, 0.08248609, 0.76091456, 0.29898644],
       [0.66232972, 0.45278835, 0.17397072, 0.92831701]])

In [7]:
np1.dtype

dtype('float64')

In [8]:
# Tensor
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.3949,  0.8595, -0.9828, -0.9066],
        [ 1.0722,  1.2878, -1.4011, -1.8638],
        [-0.3561,  0.9739,  0.0191,  0.5350]])

In [11]:
tendsor_3d = torch.zeros(2,3,4)
tendsor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
tendsor_3d.dtype

torch.float32

In [12]:
# create tensor out of numpy array

my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.3954, 0.3948, 0.1958, 0.5296],
        [0.5943, 0.0825, 0.7609, 0.2990],
        [0.6623, 0.4528, 0.1740, 0.9283]], dtype=torch.float64)